name       : haskell-digest
version    : 0.0.1.2
release    : 2
source     :
    - http://hackage.haskell.org/package/digest-0.0.1.2/digest-0.0.1.2.tar.gz : 641717eb16392abf8965986a9e8dc21eebf1d97775bbb6923c7b7f8fee17fe11
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides efficient cryptographic hash implementations for
    strict and lazy bytestrings.
description: |
    This package provides efficient cryptographic hash implementations for strict and lazy bytestrings.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
